const badwords = {
  "fuck": "හුත්ත",
  "shit": "පකෙ",
  "bitch": "බැල්ලි",
  "bastard": "අනාථයා",
  "asshole": "ගුදය",
  "motherfucker": "අම්මට හුකනවා",
  "dick": "පයිය",
  "cock": "කුකුලා",
  "pussy": "බුජ්ජි",
  "slut": "වේසි",
  "whore": "වේසි කෙලවා",
  "son of a bitch": "බැල්ලි පුතා",
  "damn": "දියවෙන්න",
  "fucking": "හුකන",
  "fucker": "හුකන කෙනා",
  "faggot": "ගැලවුනා",
  "cunt": "අමු මැදිය",
  "dumbass": "පකයා",
  "shithead": "පක කෙල්ල",
  "cock sucker": "පයිය හුකනවා",
  "twat": "පකා",
  "douchebag": "පකාටයා",
  "wanker": "ලොක්කා",
  "prick": "අමු බල්ලො",
  "retard": "පට්ට පකයෙක්",
  "hoe": "කෙලවන්නිය",
  "suck my dick": "මගේ පයිය හුකන්න",
  "eat shit": "පක කන්න",
  "fuck off": "අයින්ව",
  "go fuck yourself": "තමන්වම හුකන්න",
  "bullshit": "පක්කුකතාව",
  "pissed off": "දැක්කාට අමාරුයි",
  "ass": "ගෙඩි",
  "dipshit": "පට්ට හුත්ත",
  "dildo": "කුකුල් පයිය",
  "balls": "බෝලේ",
  "cum": "මුණුපිට",
  "jerk off": "ලොක්කා ගන්න",
  "bastards": "අනාථයෝ",
  "assclown": "ගුද බූරුwa",
  "pussy ass": "පක ගෙඩි",
  "motherfucking": "අම්මට හුකන",
  "fucked up": "කුට්ටෙන්",
};

module.exports = badwords;
