const normalwords = {
  "come": "එන්න",
  "go": "යන්න",
  "you are a fucking slut": "ඔඹ හුකන වෙසි",
  "you are good": "ඔයා හොඳයි",
  "hello": "ආයුබෝවන්",
  "bye": "බයි",
  "please": "කරුණාකර",
  "thank you": "ස්තුතියි",
  "sorry": "කනස්සල්ල",
  "how are you": "කොහොමද?",
  "good morning": "සුබ උදෑසනක්",
  "good night": "සුභ රෑ",
  "yes": "ඔව්",
  "no": "නැහැ",
  "maybe": "එහෙම නොවෙයි",
  "I love you": "මම ඔයාට ආදරෙයි",
  "you are beautiful": "ඔයා ලස්සනයි",
  "goodbye": "ගුඩ්බයි",
  "welcome": "වෙල්කම්",
  "excuse me": "සමාවන්න",
  "how much": "කීයක්?",
  "what is your name": "ඔයාගේ නම මොකක්ද?",
  "I am sorry": "මට කනස්සල්ලයි",
  "I don’t understand": "මට තේරෙන්නේ නැහැ",
  "can you help me": "ඔයා මට උදව් කරන්න පුළුවන්ද?",
  "where is the bathroom": "වැරදි කාමරය කොහෙද?",
  "I am hungry": "මට මාලු එලවායි",
  "I am tired": "මට බරයි",
};

module.exports = normalwords;
